#!/bin/sh

if [ $# -lt 1 ] ; then
  echo "Specify base"
  exit
fi

BASE=$1
LOCAL=$BASE/local
MOUNT=/proc/chos/link/

echo "Creating directories"
mkdir $BASE
mkdir $BASE/auto
mkdir $BASE/export
mkdir $BASE/local

echo "Creating links"
for dir in "bin" "dev" "etc" "extra" "home" "initrd" "lib" "opt" "sbin" "u" "usr" "var"
do
if [ -e $BASE/$dir ] ; then
rm $BASE/$dir
fi
ln -sf $MOUNT/$dir $BASE/$dir > /dev/null 2>&1
done

ln -sf local/proc $BASE/proc
